version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
    - run: docker build -t shyd/zsh .
    - run: docker push shyd/zsh
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only: oh-my-zsh
